random_state: 42

data:
  raw_dir: data/raw
  countries: ['Spain', 'France']
  file_pattern: "Churn_Modelling_{country}.csv"

features:
  cols:
    - CreditScore
    - Age
    - Tenure
    - Balance
    - NumOfProducts
    - HasCrCard
    - IsActiveMember
    - EstimatedSalary
target: Exited

split:
  test_size: 0.25

model:
  name: random_forest  # 👈 Active model

models:
  random_forest:
    n_estimators: 152
    max_depth: 10
    random_state: 42

  logistic_regression:
    penalty: l2
    C: 1.0
    solver: liblinear
    random_state: 42

  decision_tree:
    max_depth: 8
    criterion: gini
    random_state: 42

  svm:
    kernel: rbf
    C: 1.0
    gamma: scale

  xgboost:
    n_estimators: 100
    max_depth: 6
    learning_rate: 0.1
    subsample: 0.8

model_output:
  dir: models
  filename: clf-model.joblib

evaluation:
  threshold: 0.5
  scoring_metric: f1_score

outputs:
  reports_dir: reports
  figures_dir: reports/figures
  feature_importance_csv: reports/feat_imp.csv
  metrics_file: reports/metrics.json
  processed_data_dir: data/processed
  split_data:
    X_train: data/processed/X_train.pkl
    X_test: data/processed/X_test.pkl
    y_train: data/processed/y_train.pkl
    y_test: data/processed/y_test.pkl



  
    